# Generated by Django 5.0.3 on 2024-04-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("specialization", models.CharField(max_length=255)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=100)),
                ("services", models.JSONField(default=list)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialistCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("certificate_number", models.CharField(max_length=255, null=True)),
                ("certificate_url", models.URLField(null=True)),
                (
                    "certificate",
                    models.FileField(null=True, upload_to="specialist_certificates/"),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialistEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("University", "University"),
                            ("College", "College"),
                            ("Secondary School", "Secondary School"),
                            ("Primary School", "Primary School"),
                        ],
                        max_length=255,
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("start_year", models.CharField(max_length=255)),
                ("graduation_year", models.CharField(max_length=255)),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="education_certificates/"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
