# Generated by Django 5.0.4 on 2024-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0002_specialist_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("employer_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("works_here", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
